### ISSUE TITLE
Last batch record missing

### ISSUE THREAD

**Issue by ropieur** [timescale/timescaledb-parallel-copy#17] opened 2019-03-13 14:16 UTC
**Relevant system information:**
 - OS: Ubuntu 16.04.5 LTS in Docker
 - PostgreSQLversion: psql (PostgreSQL) 10.6 (Ubuntu 10.6-1.pgdg16.04+1)
 - TimescaleDB version: plpgsql | 1.0
 - Installation method: "apt install"

**Describe the bug**
Inserting a large csv file results in a table with the last record of each batch missing.

**To Reproduce**
1. Execute timescaledb-parallel-copy with a large csv file (Personally 90,000,000 records - verified with wc -l command)
2. In psql, select count(*) from 'table-name'
2a. with default --batch-size, output is 89982000
2b. with --batch-size 4000, output is 89977500
3. In psql, select * from 'table-name' where 'primray-key-name' = 'id of last record of a batch' ; returns empty

**Expected behavior**
The number of inserted records should be the same as the number of records in CSV file

**Actual behavior**
Last record of each batch is not inserted

**Comment by erimatnor** [comment] 2019-03-13 14:17
@ropieur wasn't even aware of the "transfer issue" functionality. Thanks for pointing me to it.

**Comment by ropieur** [comment] 2019-03-13 14:42
Seems this is due to the HEADER option which, I guess, is applied on each batch, although it should be applied only on the first batch, in order to follow the same semantic as the psql COPY command. My feeling is that the copy options are blindly transferred to the COPY for each batch.

**Comment by RobAtticus** [comment] 2019-03-13 16:19
Thanks for the report, will investigate

**Comment by RobAtticus** [comment] 2019-03-13 16:24
By the way @ropieur , can you paste the exact command you ran?

We do have an option to skip the header via `--skip-header` rather than using `HEADER` in the CSV command. Maybe that's where the problem is?

**Comment by ropieur** [comment] 2019-03-14 08:27
Hello RobAtticus,
I don't see --skip-header in the help usage. Here follows the list of possible options:
  -batch-size int
  -columns string
  -connection string
  -copy-options string
  -db-name string
  -file string
  -log-batches
  -reporting-period duration
  -schema string
  -split string
  -table string                                                                                                                                             
  -truncate                                                                                                                                                 
  -verbose                                                                                                                                                  
  -version                                                                                                                                                  
  -workers int

And the version is "timescaledb-parallel-copy 0.1.0 (linux amd64)"
This explains that, likely

**Comment by ropieur** [comment] 2019-03-14 11:21
And indeed I pass --copy-options "CSV HEADER" as argument

**Comment by RobAtticus** [comment] 2019-03-14 15:34
Ah I see, I am starting the release process for an update to timescaledb-tools which should contain the new version of this tool which has `--skip-header`

**Comment by RobAtticus** [comment] 2019-03-14 19:37
Hi @ropieur , the updated version should be available in packages now. Let me know if that flag works for you.

**Comment by RobAtticus** [comment] 2019-11-18 23:41
Closing because I believe this is resolved.

**Closed by RobAtticus** 2019-11-18 23:41 UTC
Labels: need-more-info
