### ISSUE TITLE
pq: invalid input syntax for type double precision

### ISSUE THREAD

**Issue by k1ng440** [timescale/timescaledb-parallel-copy#9] opened 2018-10-18 04:06 UTC

**Comment by RobAtticus** [comment] 2018-10-19 03:45
Can you give me a few lines to work with? In a private message on slack is fine too, but I have no way to reproduce your problem with the info given.

**Comment by mathiasose** [comment] 2018-11-22 15:30
I got this error because I had `NULL` values in my CSV that were represented by empty strings. I used `--copy-options="NULL ''"` to make it understand what they were.

**Comment by RobAtticus** [comment] 2019-03-01 05:17
There seems to be a fine workaround, so I will close this unless it turns out to be a different issue. Thanks @mathiasose

**Closed by RobAtticus** 2019-03-01 05:17 UTC
